appName: ryuzu-portfolio
replicas: 1
source:
  repoURL: 'git@github.com:Y-RyuZU/ReactPortfolio.git'
  targetRevision: main
container:
  repository: ghcr.io/y-ryuzu/react-portfolio
  tag: efba20c
  port: 3000
resources:
  limits:
    cpu: "1000m"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"
